name: catan_iq
description: A Colonist.io helper
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webdriver: ^3.0.3
  chaleno: ^0.0.6
  html: ^0.15.4
  flutter_svg: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true